# Generated by Django 4.1.1 on 2022-09-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
